---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: ZmsVE9R3WKx+3my3NJ1XyFYv4+6CtornUKvSiAroqbvvlPmTIZRCXETAyajmQ4UFQ+DBHTd2hfBBMxYv5dkjJyuLYoocxc5W9v7FbjP1coFk0YplUO3LG5kayiUiI/S91KRB6hsiudcwuuOIKKnX1ib4Fa8XIMkadadN/bGLRloteVY4FphBpVbodfzUUqwhlT8ALhLfyVkDzR4PPkZpA50mPACjsrU3qJuzdt42LPaxwFCazNCHuYz0k2UjjpzFFhcYgdWNba1p1i0WB9knKBITSy9iAlRsWV483zAvkR9Lqm4m5Av8b5C77vAN9+X2ogJJALsZV8kmTwabMD/yw/zreuCkrItnWcUQlLcmBaF3O902O4raTy8V9IEL1+9oqN5HgdegwE+75CM+d1khyhfo8NRWr5XaunYiTQGxWBPUwntWT/+skPZytnema+/7YwFBJ0Fhh/ZsOESTMbCjTAqPSMmxU4LhR+cao1de9Pmerzl0dM55Lz7VCfMtNa5zHXkZPkRVGndCvWkM9HSTynit65ojZjZevUQPd6dsE1JZwCaAnUYsQNExHr1dbILioMbYIOgremgg4Lxd5TmufLD4qUktJctivbdTerqv9rr4U1jPLHkl3KEM6eBk2X/Np4vYsVQEzoLZLHylxD+cEJshIxQBBKWGd815a9k5bvQ=
  email: false
