---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "TEU75CNBgp6Rk77YGmduSPtDNe00LoZJsZDnQI9w4v6CmpKRSM4fl3dPrMRh9Kt246ggw0uVq+h2oPNUE+MB9S/5TqOYREYWXwiOs6SRvYqLbtusqee+B8x2tFVEEEEyc4hLDhZfttjSAlwMsZOVmjw0SBGYNIhHjRKsf18b3zxbqt4bfNY8y5ylOOqtFc/2ZSFf4xCQx6wE5Fya/uUltMTqPiKOeYanpbXuYMbD0bDSZMZgGb4bJ6hl1M9GA4q9hRyU1qVFvr1mIK1fwIc3X5LbxEjQSFKIF7e6NsBr0Wt5R7uVNbJMI6i6kObHJbmUnRkoslnGajURsFf1is42UfuYgASUuLbigXkfA1QcqbQUozaTkxZ05vKecypkHiAFsM5ww757JTQ4EF96+ZLvSFSu81mREUSi0BotJ45KpqHhvqneeY/K+rQHOMtZFiIhnxnAnU5tWUZUdB/PSeWnItHrILALSGnzRHV/Ki6NvGX5NcGoFvXN7IJT08ZgBxX5hCkohFhI3jBpigA7Ho7q4ejQNfTtJgzd4Fjj7SdS+e4dm0z/6Oz+RbHPgOQ5GvgTdFPF/4AYD9OZOg7VYbDgYGS7qWSfyAuX58yYFBCnTSRL58Yh0cVOpumJTD0aC32tFjlTAcGHNCt3Oj0WZB21hyNjCPLuYpDbfN68yd5cuMQ="
  email: false
