---
# tasks file for virtualbox
- name: configure yum repository
  block:
    - name: import rpm key
      rpm_key:
        state: present
        key: "{{ item }}"
      loop: "{{ virtualbox_keys }}"

    - name: place yum repository
      yum_repository:
        name: virtualbox
        description: Fedora $releasever - $basearch - VirtualBox
        baseurl: "{{ virtualbox_yum_baseurl }}"
        gpgcheck: yes
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']

- name: configure apt repository
  block:
    - name: import apt key
      apt_key:
        url: "{{ item }}"
        state: present
      loop: "{{ virtualbox_keys }}"

    - name: place apt repository
      apt_repository:
        repo: deb [arch=amd64] {{ virtualbox_apt_repository }} {{ ansible_distribution_release | lower }} contrib
        state: present
        update_cache: no
  when:
    - ansible_pkg_mgr in ['apt']

- name: install requirements
  package:
    name: "{{ virtualbox_requirements }}"
    state: present

- name: install virtualbox
  package:
    name: VirtualBox-{{ virtualbox_version }}
  notify:
    - run vboxconfig
