---
# tasks file for virtualbox
- name: import rpm key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ virtualbox_keys }}"
  loop_control:
    label: "{{ item | basename }}"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']

- name: place yum repository
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: "{{ virtualbox_yum_baseurl }}"
    gpgcheck: yes
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']

- name: place zypper repository
  zypper_repository:
    name: virtualbox
    repo: "{{ virtualbox_yum_baseurl }}"
    state: present
  when:
    - ansible_pkg_mgr in ['zypper']

- name: configure apt repository
  block:
    - name: import apt key
      apt_key:
        url: "{{ item }}"
        state: present
      loop: "{{ virtualbox_keys }}"
      loop_control:
        label: "{{ item | basename }}"

    - name: place apt repository
      apt_repository:
        repo: deb [arch=amd64] {{ virtualbox_apt_repository }} {{ ansible_distribution_release | lower }} contrib
        state: present
  when:
    - ansible_pkg_mgr in ['apt']

- name: install requirements
  package:
    name: "{{ virtualbox_requirements }}"
    state: present

- name: install virtualbox
  package:
    name: "{{ virtualbox_package }}"
    state: present
  notify:
    - run vboxconfig
