---
# tasks file for virtualbox
- name: include assert.yml
  include_tasks: assert.yml

- name: import rpm key
  rpm_key:
    state: present
    key: "{{ item }}"
  register: virtualbox_import_rpm_key
  until: virtualbox_import_rpm_key is succeeded
  retries: 3
  loop: "{{ virtualbox_keys }}"
  loop_control:
    label: "{{ item | basename }}"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']

- name: place yum repository
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: "{{ virtualbox_yum_baseurl }}"
    gpgcheck: yes
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']

- name: place zypper repository
  zypper_repository:
    name: virtualbox
    repo: "{{ virtualbox_yum_baseurl }}"
    state: present
  when:
    - ansible_pkg_mgr in ['zypper']

- name: configure apt repository
  block:
    - name: import apt key
      apt_key:
        url: "{{ item }}"
        state: present
      register: virtualbox_import_apt_key
      until: virtualbox_import_apt_key is succeeded
      retries: 3
      loop: "{{ virtualbox_keys }}"
      loop_control:
        label: "{{ item | basename }}"

    - name: place apt repository
      apt_repository:
        repo: deb [arch=amd64] {{ virtualbox_apt_repository }} {{ ansible_distribution_release | lower }} contrib
        state: present
      register: virtualbox_place_apt_repository
      until: virtualbox_place_apt_repository is succeeded
      retries: 3
  when:
    - ansible_pkg_mgr in ['apt']

- name: install requirements
  package:
    name: "{{ virtualbox_requirements }}"
    state: present
  register: virtualbox_install_requirements
  until: virtualbox_install_requirements is succeeded
  retries: 3

- name: install virtualbox
  package:
    name: "{{ virtualbox_package }}"
    state: present
  register: virtualbox_install_virtualbox
  until: virtualbox_install_virtualbox is succeeded
  retries: 3
  notify:
    - run vboxconfig
